//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glassdoor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_Created { get; set; }
        public int User_ID { get; set; }
        public int Job_ID { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
